import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@/components/ui/navigation";

export const metadata: Metadata = {
  title: "Gym bro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <Navigation />
      </body>
    </html>
  );
}
